### PR TITLE
Added products

### PR DESCRIPTION
**Pull request by dev-johnson01**
A user interface to add a new product.
The JIRA link is https://terisolve.atlassian.net/browse/PRODH-42

add-product

### CODE REVIEW

**Review by jsamchineme — COMMENTED** [review]
put more details into this PR description, including a screenshot, and the JIRA link

**Comment by dev-johnson01** [comment]
A user inteerface to add a new product.
The interface has 

- a text input for product name

-  a text area for product description and

-  a file upload button to upload the product image banner.

The JIRA link is https://terisolve.atlassian.net/browse/PRODH-42

add-product

**Comment by jsamchineme** [comment]
@dev-johnson01 please remove the add-product.png file you added. it's not needed as a file. I meant that the screenshot should be uploaded into the description of the PR above.

**Comment by dev-johnson01** [comment]
I just saw your update now sir, it seems you have removed it from the
repository at your end.

**Pull request merged**
